#!/usr/bin/env bash
# Display a list of currently running processes
# - Includes all processes, for all users, including those which might not have a TTY
# - Displays in a user-oriented format
# - Shows process hierarchy

# Using ps to list all processes and their attributes
ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command
