#!/usr/bin/env bash
# Stop the process named "4-to_infinity_and_beyond"
process_name="4-to_infinity_and_beyond"
pids=$(pgrep -f "$process_name")

for pid in $pids; do
    echo "Terminating process $pid"
    if ps -p $pid > /dev/null; then
        pkill -P $pid   
        kill -TERM $pid 
    else
        echo "Process $pid not found."
    fi
done
