#!/usr/bin/env bash
# Stop the process named "7-highlander"
process_name="7-highlander"
pids=$(pgrep -f "$process_name")

for pid in $pids; do
    echo "Terminating process $pid"
    kill -TERM "$pid"
done
