#!/bin/bash
# Function to handle SIGTERM signal
invincible_message() {
    echo "I am invincible!!!"
}

# Register SIGTERM handler
trap 'invincible_message' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done

