#!/bin/bash
# Function to handle SIGTERM signal
invincible_message() {
    echo "I am invincible!!!"
}

trap 'invincible_message' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

