#!/usr/bin/env bash
# Function to check if the process is running and kill it
kill_process() {
    process_name="7-highlander"
    pids=$(pgrep -f "$process_name")
    
    if [ -n "$pids" ]; then
        echo "Terminating process $process_name"
        pkill -f "$process_name"
    fi
}

# Run the process 7-highlander
./7-highlander &

# Wait for a while before checking and killing the process
sleep 5

# Check if the process is running and kill it
kill_process
