#!/usr/bin/env bash
# This script displays information about each user in /etc/passwd
# Check if the file exists
if [ -e "/etc/passwd" ]; then
    # Read the file line by line
    while IFS=: read -r username _ uid gid _ homedir shell; do
        # Get the group name corresponding to the group ID
        group=$(getent group "$gid" | cut -d ':' -f 1)
        
        # Get the user's password
        password=$(grep "^$username:" /etc/shadow | cut -d ':' -f 2)
        
        # Remove leading and trailing whitespace from the password
        password=$(echo "$password" | tr -d '[:space:]')
        
        # Print the user information
        echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $username"
    done < "/etc/passwd"
else
    echo "File /etc/passwd does not exist"
fi
