#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data
# Using awk to extract the visitor IP and HTTP status code from the Apache log file
# Then, counting the occurrences and sorting them
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
