#!/usr/bin/env bash
# Correct server configuration issue
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
# Restart the Nginx service
su nginx -s /bin/bash -c 'service nginx restart'
